---
meta:
  name:    shield-addon-mysql
  release: S.H.I.E.L.D. MySQL / MariaDB Addon
  target:  sw
  url:     https://ci.starkandwayne.com

  manifest:
    path: ci/manifest.yml

  git:
    email: ci@starkandwayne.com
    name:  Stark & Wayne CI Bot

  bosh-lite:
    target: https://10.58.111.49:25555
    username: (( vault "secret/bosh-lites/lite49/users/admin:username" ))
    password: (( vault "secret/bosh-lites/lite49/users/admin:password" ))
    cacert:   (( vault "secret/bosh-lites/lite49/certs:rootCA.pem" ))

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  shieldproject
    repo:   shield-addon-mysql-boshrelease
    branch: master
    private_key:  (( vault "secret/pipelines/shared/shield-bot/github:private" ))
    access_token: (( vault "secret/pipelines/shared/shield-bot/github:access_token" ))

  slack:
    webhook: (( vault "secret/pipelines/shield-addon-mysql-boshrelease/slack:webhook" ))
    channel: '#shield'
    username:      starkandwayne-ci
    icon:          https://www.starkandwayne.com/assets/images/shield-blue-50x50.png


jobs:
- name: testflight
  serial_groups: [bosh]
