---
meta:
  name:    shield-addon-mysql
  release: S.H.I.E.L.D. MySQL / MariaDB Addon
  target:  shield@pipes
  url:     https://pies.starkandwayne.com

  manifest:
    path: ci/manifest.yml

  git:
    email: ci@starkandwayne.com
    name:  Stark & Wayne CI Bot

  bosh-lite:
    target:   https://10.200.131.9:25555
    username: admin
    password: (( vault "secret/thunder/dome/bosh/users/admin:password" ))
    cacert:   (( vault "secret/thunder/dome/bosh/ssl/ca:certificate" ))

  aws:
    access_key: (( vault "secret/pipelines/aws/cf-community:access" ))
    secret_key: (( vault "secret/pipelines/aws/cf-community:secret" ))

  github:
    owner:  shieldproject
    repo:   shield-addon-mysql-boshrelease
    branch: master
    private_key:  (( vault "secret/pipelines/github/starkandwayne/shield-bot:private" ))
    access_token: (( vault "secret/pipelines/github/starkandwayne/shield-bot:access_token" ))

  shout:
    url:      http://10.200.131.1:7109
    username: ops
    password: (( vault "secret/buffalo/lab/concourse/shout/ops:password" ))
