---
meta:
  name:    shield-addon-mysql
  release: S.H.I.E.L.D. MySQL / MariaDB Addon
  target:  shield@pipes
  url:     https://pies.starkandwayne.com

  manifest:
    path: ci/manifest.yml

  git:
    email: ci@starkandwayne.com
    name:  Stark & Wayne CI Bot

  bosh-lite:
    target:   ((bosh.url))
    username: ((bosh.username))
    password: ((bosh.password))
    cacert:   ((bosh.ca-certificate))

  aws:
    access_key: ((aws.access_key_id))
    secret_key: ((aws.secret_access_key))

  github:
    owner:  shieldproject
    repo:   shield-addon-mysql-boshrelease
    branch: master
    private_key:  ((github.private_key))
    access_token: ((github.access_token))

  shout:
    url:      ((shout.url))
    username: ((shout.username))
    password: ((shout.password))
